email: "jose.tobias@outlook.com"
author: "José Tobias"
twitter_username: "none"
github_username: "aprendereconomia"

# Build settings
plugins: [jekyll-paginate-v2, jekyll-archives]
markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

pagination:
  enabled: true 
  debug: false  
  collection: 'posts'
  per_page: 3
  permalink: '/page/:num/'
  sort_field: 'date'
  
  extension: html
  indexpage: 'index'

    
# URL config
permalink: pretty

# plugins config
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

# defaults config
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
