email: "jose.tobias@outlook.com"
author: "José Tobias"
twitter_username: "none"
github_username: "aprendereconomia"

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

# URL config
permalink: pretty

# defaults config
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
